stage4x4: # IMAGE_SIZE = 4, 8, 16, 32, 64, 128, 256, 512
  supervisor:
    args:
      version: 0
      name: Optimize4x4
      checkpoint: d:checkpoints
  data:
    train:
      transforms:
        - [torchvision.transforms, CenterCrop, {size: [512, 512]}]
        - [torchvision.transforms, Resize, {size: [4, 4]}]
        - [torchvision.transforms, ToTensor, {}]
        - [torchvision.transforms, RandomHorizontalFlip, {p: 0.5}]
        - [torchvision.transforms, Normalize, {mean: [.5, .5, .5], std: [.5, .5, .5]}]
      dataloader:
        args:
          batch_size: 256
  models:
    netG:
      args: 
        latent_channels: [512]
    netD:
      args: 
          latent_channels: [512]
  optimizers:
  loss:
    lossG:
      - [1.0, losses.generator_loss, MeanDiscriminatorLoss, {}]
    lossD:
      - [<WD>, losses.discriminator_loss, WassersteinDistance, {scale: <SCALE_WD>}]
      - [<GP>, losses.discriminator_loss, GradientPenalty, {}]
  optG:
    module: torch.optim
    name: Adam
    target: netG
    args:
      lr: <LEARNING_RATE_G>
      betas: [<BETA_1_G>, <BETA_2_G>]
  optD:
    module: torch.optim
    name: Adam
    target: netD
    args:
      lr: <LEARNING_RATE_D>
      betas: [<BETA_1_D>, <BETA_2_D>]
  score: 
    - [1.0, FID]
  hooks:
    - [hooks.load, Resume, {targets: {netG: generator.pkl, netD: discriminator.pkl, optG: optimizer_generator.pkl, optD: optimizer_discriminator.pkl, meta: meta.json}, dir: latest}]
    - [hooks.save, SaveToDir, {every: 10, targets: {netG: generator.pkl, netD: discriminator.pkl, optG: optimizer_generator.pkl, optD: optimizer_discriminator.pkl, meta: meta.json}, dir: latest}]
    - [hooks.save, SaveAll, {every: 10, targets: {netG: generator.pkl, netD: discriminator.pkl, optG: optimizer_generator.pkl, optD: optimizer_discriminator.pkl, meta: meta.json}}]
    - [hooks.gan_hooks, TensorboardGenerateImageSample, {every: 10, target_model: netG, samples: 64}]
    - [hooks.gan_hooks, TensorboardScalarData, {every: 10, targets: [loss_disc,  loss_gen]}]
    - [hooks.gan_hooks, TensorboardFID, {every: 10, generator: netG, data: train, samples: 1000, name: FID}]
    - [hooks.gan_hooks, TensorboardLFDS, {every: 10, encoder: netD, generator: netG, data: train, samples: 1000}]
    - [hooks.gan_hooks, TensorboardImageStatsCosineSimilarity, {every: 10, generator: netG, data: train, samples: 1000}]
    - [hooks.save, SaveBest, {every: 10, targets: {netG: generator.pkl, netD: discriminator.pkl, optG: optimizer_generator.pkl, optD: optimizer_discriminator.pkl, meta: meta.json}}]
    - [hooks.gan_hooks, ConsoleStats, {every: 1, targets: [loss_disc,  loss_gen]}]

parameters:
  LEARNING_RATE_G: [float, 0.00001, 0.001, log]
  LEARNING_RATE_D: [float, 0.00001, 0.001, log]
  BETA_1_G: [float, 0.0, 1, uniform]
  BETA_2_G: [float, 0.0, 1, uniform]
  BETA_1_D: [float, 0.0, 1, uniform]
  BETA_2_D: [float, 0.0, 1, uniform]
  WD: [float, 0.0, 2.0, uniform]
  GP: [float, 0.0, 20.0, uniform]
  SCALE_WD: [float, 0.0001, 0.01, log]
trials: 100
db: sqlite:////d:checkpoints/Optimize4x4/optuna.db
```

